### ISSUE TITLE
Morning session: Peer-to-peer code review Week 5  Day 5 Module 1

### ISSUE THREAD

**Issue by mike2611** [lfmnovaes/conference#2]
## Your code is great :robot: 
# We have some little suggestions to give you.

**Comment by mike2611** [comment]
## Recommendation
- Hi @ifmnovaes your project looks amazing, I only have a small recommendation in order for your project to follow the requirements more precisely, you can change the icon of your hamburger button for your navbar to an "X" close icon when the user clicks on the button. 
https://github.com/lfmnovaes/conference/pull/1/files#diff-2212b84a2a6ffe239872c76d266680d86f2438391034b2eb19604f17104f6968R15 
![image](https://user-images.githubusercontent.com/28109626/132870479-9316dbe6-ae52-48ff-875d-2c84a4c5bafa.png)

## Happy Coding :robot: :+1:

**Comment by ramiaquista** [comment]
## Awesome Job Luis! 😄

### I think you have made an incredible job, I would only suggest making 2 minors changes that could improve your HTML Dry: ♻️

- I would recommend to change this HTML structure: 
<img width="644" alt="Screen Shot 2021-09-10 at 11 28 31 AM" src="https://user-images.githubusercontent.com/24655018/132869615-be7bd4b8-dd63-40db-86a7-b22be860e0f6.png">
 - By something like this:
<img width="644" alt="Screen Shot 2021-09-10 at 11 32 30 AM" src="https://user-images.githubusercontent.com/24655018/132870249-5f3691bb-71ee-4e3f-826a-6f7717f08ab4.png">

- The other change I would recommend to do is to apply some margin-bottom to events images, changing this: 
<img width="294" alt="Screen Shot 2021-09-10 at 11 33 52 AM" src="https://user-images.githubusercontent.com/24655018/132870421-037f516e-5ba3-404b-8298-57f027f680c2.png">
- By something like this:
<img width="294" alt="Screen Shot 2021-09-10 at 11 36 13 AM" src="https://user-images.githubusercontent.com/24655018/132870790-040afa81-60ab-4d7e-9204-563ce3a96840.png">

### You have made an incredible job, keep coding 😄😄

**Comment by lfmnovaes** [comment]
Fixed those issues, thanks for the feedback. 😃
